// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('./../components/shared/form/BaseButton.vue')['default']
    BaseInput: typeof import('./../components/shared/form/BaseInput.vue')['default']
    BaseTextarea: typeof import('./../components/shared/form/BaseTextarea.vue')['default']
    BlankView: typeof import('./../components/BlankView.vue')['default']
    Datatable: typeof import('./../components/shared/data/Datatable.vue')['default']
    DialogEditUser: typeof import('./../components/dialogs/DialogEditUser.vue')['default']
    DialogTest: typeof import('./../components/dialogs/DialogTest.vue')['default']
    Dropdown: typeof import('./../components/shared/overlay/Dropdown.vue')['default']
    DropdownItem: typeof import('./../components/shared/overlay/DropdownItem.vue')['default']
    FieldGroup: typeof import('./../components/shared/form/FieldGroup.vue')['default']
    Layout: typeof import('./../components/Layout.vue')['default']
    Modal: typeof import('./../components/shared/overlay/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('./../components/shared/overlay/Toast.vue')['default']
    ToastGroup: typeof import('./../components/shared/overlay/ToastGroup.vue')['default']
  }
}
